# Task 2
* Запитайте в користувача верхню та нижню межу діапазону чисел.
* Створіть квадратну матрицю 5×5 з цілими значеннями в цьому діапазоні.
* Виведіть вихідну матрицю.
* Отримайте головну діагональ і виведіть діагональні елементи.
* Підрахуйте суму елементів головної діагоналі та виведіть результат.
* Обнуліть елементи строго вище головної діагоналі та виведіть змінену матрицю.

In [1]:
import numpy as np

In [2]:
top_limit = int(input('enter the top limit: '))
bottom_limit = int(input('enter the bottom limit: '))

enter the top limit:  20
enter the bottom limit:  5


In [3]:
matrix = np.random.randint(bottom_limit, top_limit, size=25).reshape(5,5)
print(matrix)

[[19  8  5 18  8]
 [11  6 16 14 17]
 [10 10 16 19  6]
 [17  8 12 13  5]
 [10 10 13 15 18]]


In [4]:
main_diag = np.diag(matrix)
print(main_diag)

[19  6 16 13 18]


### Sum of the main diagonal elements

In [5]:
print(sum(main_diag))

72


In [7]:
for i in range(1, 5):
    np.fill_diagonal(matrix[:-i, i:], 0)

In [8]:
print(matrix)

[[19  0  0  0  0]
 [11  6  0  0  0]
 [10 10 16  0  0]
 [17  8 12 13  0]
 [10 10 13 15 18]]
