# Task 3
Запитайте у користувача початок і кінець діапазону чисел.
* Сформуйте послідовність цілих чисел у вказаному діапазоні.
* Перетворіть послідовність на матрицю розміром 6×5 і виведіть її.
* Підрахуйте суму елементів у кожному рядку і виведіть отриманий одновимірний масив сум.
* Визначте максимальні значення за кожним стовпчиком і виведіть отриманий одновимірний масив максимумів.

In [1]:
import numpy as np

In [5]:
start_val = int(input("Enter start: "))
end_val = int(input("Enter end: "))

Enter start:  10
Enter end:  20


In [6]:
arr3 = np.random.randint(start_val, end_val + 1, 30)

In [7]:
matrix3 = arr3.reshape(6, 5)
print(matrix3)

[[16 17 11 19 13]
 [12 18 13 18 11]
 [12 10 12 15 20]
 [11 18 18 12 10]
 [12 13 14 12 18]
 [15 13 15 18 12]]


In [9]:
row_sums = matrix3.sum(axis=1)
print('Sums:', row_sums)

Sums: [76 72 69 69 69 73]


In [11]:
col_maxes = matrix3.max(axis=0)
print('Max values: ', col_maxes)

Max values:  [16 18 18 19 20]


# Task 4
Запитайте в користувача діапазон значень (нижню і верхню межу), включно з від'ємними числами.
* Створіть одновимірний масив із 15 випадкових цілих чисел у вказаному діапазоні.
* Виведіть вихідний масив.
* Виділіть усі від'ємні елементи та виведіть їх як окремий масив.
* Створіть змінену копію масиву, в якій від'ємні елементи замінено на нулі, і виведіть її.
* Підрахуйте кількість нульових елементів у зміненому масиві та виведіть результат.

In [12]:
low_val = int(input("Enter low: "))
high_val = int(input("Enter high: "))

Enter low:  -50
Enter high:  50


In [13]:
arr4 = np.random.randint(low_val, high_val + 1, 15)
print(arr4)

[  7   5 -48  41  34 -39 -43 -34  -5  43  41 -17  10 -46  -3]


In [14]:
negative_arr = arr4[arr4 < 0]
print('Negative: ', negative_arr)

Negative:  [-48 -39 -43 -34  -5 -17 -46  -3]


In [15]:
modified_arr4 = np.where(arr4 < 0, 0, arr4)
print('Without negative: ', modified_arr4)

Without negative:  [ 7  5  0 41 34  0  0  0  0 43 41  0 10  0  0]


In [16]:
zeros_count = np.sum(modified_arr4 == 0)
print('Zeros count: ', zeros_count)

Zeros count:  8


# Task 5
Запитайте в користувача довжину масивів.
* Створіть два одновимірні масиви вказаної довжини:
* перший заповніть випадковими числами від 0 до 10;
* другий заповніть випадковими числами від 10 до 20.
* Виведіть обидва вихідні масиви.
* Об'єднайте масиви в один і виведіть результат.
* Виконайте поелементне додавання та поелементну різницю вихідних масивів і виведіть обидва результати.

In [17]:
arr_length = int(input("Enter lenght of array: "))

Enter lenght of array:  10


In [18]:
arr5_1 = np.random.randint(0, 11, arr_length)
arr5_2 = np.random.randint(10, 21, arr_length)

In [19]:
print("arr1:\n", arr5_1)
print("arr2:\n", arr5_2)

arr1:
 [ 1  5  7  2 10  1  2  3  9  4]
arr2:
 [13 13 13 20 19 16 20 19 12 10]


In [20]:
combined_arr = np.concatenate((arr5_1, arr5_2))
print('Combined: ', combined_arr)

Combined:  [ 1  5  7  2 10  1  2  3  9  4 13 13 13 20 19 16 20 19 12 10]


In [22]:
print(arr5_1 + arr5_2)
print(arr5_1 - arr5_2)

[14 18 20 22 29 17 22 22 21 14]
[-12  -8  -6 -18  -9 -15 -18 -16  -3  -6]


# Task 6
Запитайте у користувача розмірність вихідної матриці (наприклад, 4×6).
* Створіть матрицю з послідовно зростаючих цілих чисел заданої розмірності.
* Виведіть вихідну матрицю.
* Запитайте в користувача нові розміри (наприклад, 2×12) і перетворіть матрицю в зазначену форму.
* Виведіть отриману матрицю.
* Визначте мінімальні та максимальні значення в кожному рядку нової матриці та виведіть обидва одновимірні масиви.
* Підрахуйте загальну суму всіх елементів нової матриці та виведіть результат.

In [26]:
r, c = map(int, input("Enter size: ").split('x'))

Enter size:  2x5


In [27]:
matrix = np.arange(1, r * c + 1).reshape(r, c)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [28]:
nr, nc = map(int, input("Enter new size: ").split('x'))
reshaped = matrix.reshape(nr, nc)
print(reshaped)

Enter new size:  5x2


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [30]:
print("Min in rows:", reshaped.min(axis=1))
print("Max in rows:", reshaped.max(axis=1))
print("Total sum elements:", reshaped.sum())

Min in rows: [1 3 5 7 9]
Max in rows: [ 2  4  6  8 10]
Total sum elements: 55
