# Task 1
Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
* Збережіть масив у змінну і виведіть його на екран.
* Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
* Відсортуйте масив за зростанням і виведіть результат.
* Відобразіть масив до і після сортування.

In [1]:
import numpy as np

In [2]:
rand10 = np.random.randint(1, 100, size=10)
rand10

array([83, 94, 68, 28, 56, 26,  7,  9, 47, 51], dtype=int32)

In [3]:
print("мінімальне: %d, максимальне %d та середнє значення масиву %f" % (
    np.min(rand10), 
    np.max(rand10), 
    np.mean(rand10)
))

мінімальне: 7, максимальне 94 та середнє значення масиву 46.900000


In [4]:
print(rand10, np.sort(rand10), sep='\n')

[83 94 68 28 56 26  7  9 47 51]
[ 7  9 26 28 47 51 56 68 83 94]


# Task 2
Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
* Виведіть масив у читабельному вигляді (у вигляді таблиці).
* Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
* Визначте загальне середнє значення масиву.
* Виведіть усі результати в зручному вигляді
(наприклад: "Суми за рядками: ...","Суми за стовпцями: ...")


In [5]:
rand_4_4 = np.random.randint(1, 50, size=(4,4))
rand_4_4

array([[11, 41, 34, 33],
       [ 7, 26, 28,  6],
       [37, 44, 22, 28],
       [ 5, 37, 25, 34]], dtype=int32)

In [6]:
print(np.sum(rand_4_4, axis=0),  # columns
      np.sum(rand_4_4, axis=1),  # rows
      np.mean(rand_4_4))

[ 60 148 109 101] [119  67 131 101] 26.125


In [7]:
print(*["%s - %d" % (k,v) for (k,v) in zip(rand_4_4, np.sum(rand_4_4, axis=1))], sep='\n')
print(np.sum(rand_4_4, axis=0), "- %f " % np.mean(rand_4_4))

[11 41 34 33] - 119
[ 7 26 28  6] - 67
[37 44 22 28] - 131
[ 5 37 25 34] - 101
[ 60 148 109 101] - 26.125000 


# Task 3
* Створіть масив розміром 3×5, заповнений числами від 0 до 14.
* Виведіть вихідний масив.
* Виконайте транспонування масиву (рядки стають стовпцями, а стовпці — рядками).
* Застосуйте операцію reshape, щоб отримати масив 5×3.
* Відобразіть результати на екран.

In [8]:
arr = np.random.randint(0, 14, size=(3,5))
print(arr)

[[ 1 11  9  1  4]
 [13 10 10  1 13]
 [ 2  5 11  3  8]]


In [9]:
print('Transpose:\n', np.transpose(arr))
print(f'Shape of array: {arr.shape}')

Transpose:
 [[ 1 13  2]
 [11 10  5]
 [ 9 10 11]
 [ 1  1  3]
 [ 4 13  8]]
Shape of array: (3, 5)


In [10]:
print(arr.reshape(5,3))
print(f'Shape of transoped array: {arr.reshape(5, 3).shape}')

[[ 1 11  9]
 [ 1  4 13]
 [10 10  1]
 [13  2  5]
 [11  3  8]]
Shape of transoped array: (5, 3)


# Task 4
* Створіть масив розміром 10×10, заповнений випадковими числами з плаваючою крапкою від 0 до 1.
* Знайдіть мінімальне та максимальне значення в усьому масиві.
* Визначте індекси мінімального та максимального елементів
* (наприклад: (рядок, стовпець)).
* Виведіть сам масив і окремо знайдені значення разом з їхніми індексами.

In [16]:
arr2 = np.random.rand(10, 10)
np.set_printoptions(precision=4)
print(arr2)
# print(f'{arr2[index_max]}, index: {index_max}\n{arr2[index_min]}, index: {index_min}')

[[6.2665e-01 1.9524e-01 8.2290e-02 2.0266e-01 7.4211e-01 6.2097e-01
  2.9020e-01 1.0491e-01 2.0887e-01 4.9155e-01]
 [4.5604e-01 1.7318e-04 9.9309e-01 6.2215e-01 5.8932e-01 5.4700e-01
  4.1617e-01 5.9325e-01 9.7721e-01 8.8432e-01]
 [8.6974e-01 7.2485e-01 7.4756e-01 3.2799e-01 5.5395e-01 6.0338e-01
  5.9406e-01 9.2640e-01 6.2812e-01 2.2615e-01]
 [1.2897e-02 7.2945e-01 7.9517e-01 8.7670e-01 9.1824e-01 5.7481e-02
  4.0326e-01 2.0079e-01 1.5991e-01 5.7683e-01]
 [4.6503e-01 7.0946e-01 3.6149e-01 8.2725e-01 5.5217e-01 7.0587e-01
  7.7648e-01 1.0180e-01 3.9021e-01 4.4539e-01]
 [1.3034e-01 9.5189e-01 3.1957e-01 1.4639e-01 5.0534e-01 5.4040e-01
  1.1224e-02 9.4529e-01 2.8138e-01 8.8615e-01]
 [6.4153e-01 8.4689e-01 2.2308e-01 8.1743e-01 1.4358e-01 2.7664e-01
  7.2464e-01 3.4768e-01 9.3962e-01 6.0113e-01]
 [5.2113e-01 2.8534e-01 9.4885e-01 8.6044e-01 1.4520e-01 6.0116e-01
  4.6172e-01 7.4204e-01 3.8394e-01 2.3252e-01]
 [6.1423e-01 1.2536e-01 8.0281e-02 9.8355e-02 1.9562e-01 7.6166e-01
  7.1470e-01

In [36]:
arr_max = np.max(arr2)
arr_min = np.min(arr2)
print(f'Max: {arr_max}')
print(f'Min: {arr_min}')
arr_max_i = np.argmax(arr2)
arr_min_i = np.argmin(arr2)
print(f'Max index: {arr_max_i}')
print(f'Min index: {arr_min_i}')
max_coord = np.unravel_index(arr_max_i, arr2.shape)
min_coord = np.unravel_index(arr_min_i, arr2.shape)
print(f'Coordinate max element: {', '.join(map(str, max_coord))}')
print(f'Coordinate min element: {', '.join(map(str, min_coord))}')

Max: 0.9930935726583214
Min: 0.00017317582760845163
Max index: 12
Min index: 11
Coordinate max element: 1, 2
Coordinate min element: 1, 1


# Task 5
* Створіть одновимірний масив із 15 випадкових цілих чисел від -10 до 10.
* Виведіть масив.
* За допомогою булевої індексації виберіть тільки додатні елементи.
* За допомогою булевої індексації виберіть тільки парні елементи.
* Виведіть обидва результати на екран.


In [37]:
arr3 = np.random.randint(-10, 10, size=15)
print(arr3)

[-3  5  0  5  7  3 -8 -2  3  8  5  4 -8  4 -5]


In [39]:
print(arr3[arr3 > 0])

[5 5 7 3 3 8 5 4 4]


### Count of nonzero elements

In [51]:
print(np.count_nonzero(arr3[arr3]))

14


In [40]:
print(arr3[arr3 % 2 == 0])

[ 0 -8 -2  8  4 -8  4]


# Task 6
* Створіть два одновимірні масиви довжиною 5: перший заповніть числами від 1 до 5, другий — числами від 6 до 10.
* Об'єднайте їх в один масив за допомогою np.concatenate.
* Побудуйте двовимірний масив 2×5, у якому перший рядок — перший масив, а другий рядок — другий масив.
* Об'єднайте обидва масиви в одну колонку (розмірність 5×2).
* Виведіть усі три результати на екран.


In [43]:
arr5 = np.random.randint(1, 5, size=5)
arr6 = np.random.randint(6, 10, size=5)
conc = np.concatenate((arr5, arr6), axis=0)
print(arr5, arr6)
print(conc)

[4 1 3 4 2] [8 9 6 7 8]
[4 1 3 4 2 8 9 6 7 8]


In [45]:
matrix = conc.reshape(2,5)
print(matrix)

[[4 1 3 4 2]
 [8 9 6 7 8]]


In [50]:
print(np.transpose(matrix))

[[4 8]
 [1 9]
 [3 6]
 [4 7]
 [2 8]]
